server:
  port: 8080

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth-service route
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader

        # Tenant-service route
        - id: multi-tenant-service
          uri: lb://multi-tenant-service
          predicates:
            - Path=/tenant/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader

        # Resident-service route
        - id: resident-service
          uri: lb://resident-service
          predicates:
            - Path=/resident/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
            - StripPrefix=0
        
        # Service-catalog-service route
        - id: service-catalog-service
          uri: lb://service-catalog-service
          predicates:
            - Path=/services/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
        
        # Contract-service route
        - id: contract-service
          uri: lb://contract-service
          predicates:
            - Path=/contract/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader

        # Notification-service route
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notify/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
        
        # Payment-service route
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
            - Path=/api/**
            - Path=/sandbox/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
        # Monitoring-service route
        - id: monitoring-service
          uri: lb://monitoring-service
          predicates:
            - Path=/monitoring/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

jwt:
  secret: mysecretkeymysecretkeymysecretkey123

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG